### ISSUE TITLE
 Best AwesomeWM Configuration on Github

### ISSUE THREAD

**Issue by Thomashighbaugh** [Mofiqul/awesome-config#2]
**Note**:Will close in a few days (if I remember) if you don't. 

Just wanted to say, this is perhaps the most functional, well designed and modular **AwesomeWM** configuration I have evaluated (and I have evaluated most of them I can find), which has inspired me to rewrite my own configuration again in hopes of achieving something similar in terms of how it functions under the hood, without any significant performance lag and relatively easy modification of the source code without transient errors popping up across the configuration (with the bonus of not having directories named noodle or anything obnoxious like that thankfully). 

Instead of focusing on making it a trending *r/unixporn* post, you made a truly functional configuration which is well commented and the purposes behind its various portions are easily deduced while retaining the form of typical awesome configurations and **lua** code in general. If not presently engaged in writing **lua** professionally, sir I think you should be because you write it about as well as anyone I've seen. 

I am about as impressed with this work as I am with anything on the planet, I can't thank you enough for writing this and given time, that **68 stars** you have earned will magnify several factors of ten because you have on your hands the best kept secret in awesome window manager configurations.  

PS thank you for not naming something horrible like "Glorious", awesome-shell is fitting and tasteful. 

_**Cheers**_,
##### Thomas Leon Highbaugh

**Comment by Mofiqul** [comment]
Thanks a lot. I really appreciate that you liked my work. After using bspwm and i3-gaps for a long period of time I realized that I want something more from my desktop experience, something like a DE but without losing any performance and my tiling workflow. So I made the switch to awesome wm and started awesome-shell. 
There are still so may rooms for improvements, and I am open to any suggestion and PR
