### ISSUE TITLE
Enable rounded corners on windows

### ISSUE THREAD

**Issue by ejuarezg** [Mofiqul/awesome-config#7]
Hi @Mofiqul 

I've started using your dotfiles and I think they are really great. I had a quick question,

How would I enable rounded corners on windows?

Thanks!

**Comment by Mofiqul** [comment]
For rounded corner on clients remove [this](https://github.com/Mofiqul/awesome-shell/blob/c479d274dd9723322b7bac070d3d8f1ee9964da6/configurations/picom.conf#L119) from `picom.conf`

Make sure you are using [picom-ibhagwan-git](https://github.com/ibhagwan/picom)

**Comment by ejuarezg** [comment]
Thank you! It actually turned out to be the next line, the one with `"class_g != 'awesome'",`, but your comment helped me find it. Feel free to close this issue.
